server:
  port: 18081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dubbo-demo?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-provider
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
dubbo:
  protocol:
    port: 20881 # 端口
    name: dubbo # 名字
  registry:
    address: nacos://127.0.0.1:8848 # 注册中心地址
  scan:
    base-packages: cn.itcast.user.service # dubbo注解包扫描